services:
  sagemath:
    image: sagemath/sagemath:10.4
    container_name: sagemath-numtheory
    ports:
      - "127.0.0.1:8809:8888"
    volumes:
      - ./work:/home/sage/work
      - ./jupyter:/home/sage/.jupyter
    entrypoint: ["sage"]
    command:
      - -n
      - jupyterlab
      - --ip=0.0.0.0
      - --port=8888
      - --notebook-dir=/home/sage/work
      - --no-browser
      - --ServerApp.token=
      - --IdentityProvider.token=
